export const TOOLTIPS = Object.freeze({
  newPost: "Create a new post",
  liked: "Your liked posts",
  users: "Everyone on Post Panel",
  signIn: "Sign in with GitHub",
  profile: "Open your profile",
  signOut: "Sign out",
  backToPosts: "Back to all posts",
  back: "Go back",
  goToTop: "Back to top",
  close: "Close",
  like: "Like this post",
  unlike: "Remove your like",
  generateAI: "Generate the post content with AI",
  cancel: "Discard changes",
  createPost: "Publish post",
  saveChanges: "Save changes",
  save: "Save",
  cancelEdit: "Cancel editing",
  viewSource: "View source on GitHub",
  playNow: "Play this project",
  visitSite: "Visit this site",
  prevImage: "Previous image",
  nextImage: "Next image",
  editPost: "Edit post",
  deletePost: "Delete post",
  viewPost: "Open post",
  details: "View details",
  editComment: "Edit comment",
  deleteComment: "Delete comment",
  postComment: "Post comment",
  seeAllComments: "Load all comments",
  deleteAllPosts: "Delete all posts",
  deleteAllUsers: "Delete all users",
  adminLogout: "Sign out of admin",
  adminRefresh: "Refresh dashboard",
  adminLogin: "Sign in to the admin panel",
  openInNewTab: "Open in a new tab",
  goLogin: "Sign in with GitHub first",
  goHome: "Go back to the home page",
  edit: "Edit",
  view: "View post",
  github: "Open on GitHub",
  delete: "Delete",
  cancelAction: "Cancel",
  deleteAll: "Delete everything",
  editorLab: "Experimental block editor (custom Quill)",
  fetchInfo: "Fetch repository info from GitHub",
  moveUp: "Move block up",
  moveDown: "Move block down",
  removeBlock: "Remove this block",
  addBlock: "Add a paragraph block",
  addHeading: "Add a heading block",
  addImage: "Add an image block",
  addVideo: "Add a video block",
  copyMarkdown: "Copy edited content as markdown",
  copyHtml: "Copy edited content as HTML",
})